//https://api.twitch.tv/kraken/search/channels?query=*
const channels = {
    {
    "_total": 111722296,
    "_links": {
        "self": "https://api.twitch.tv/kraken/search/channels?limit=10&query=%2A",
        "next": "https://api.twitch.tv/kraken/search/channels?limit=10&offset=10&query=%2A"
    },
    "channels": [
        {
            "mature": false,
            "partner": false,
            "status": "Do you even stream bro?!",
            "broadcaster_language": "en",
            "display_name": "Syndicate",
            "game": "H1Z1: King of the Kill",
            "language": "en",
            "_id": 16764225,
            "name": "syndicate",
            "created_at": "2010-10-17T23:19:43Z",
            "updated_at": "2017-02-04T20:07:04Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/syndicate-profile_image-03bf1d6ad0025f86-300x300.png",
            "banner": null,
            "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/syndicate-channel_offline_image-a15fc19d9828b9c7-1920x1080.png",
            "background": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/syndicate-profile_banner-5f912a83f7e9bafe-480.png",
            "profile_banner_background_color": null,
            "url": "https://www.twitch.tv/syndicate",
            "views": 39109112,
            "followers": 2463357,
            "_links": {
                "self": "https://api.twitch.tv/kraken/channels/syndicate",
                "follows": "https://api.twitch.tv/kraken/channels/syndicate/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/syndicate/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/syndicate/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/syndicate",
                "features": "https://api.twitch.tv/kraken/channels/syndicate/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/syndicate/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/syndicate/editors",
                "teams": "https://api.twitch.tv/kraken/channels/syndicate/teams",
                "videos": "https://api.twitch.tv/kraken/channels/syndicate/videos"
            }
        },
        {
            "mature": false,
            "partner": false,
            "status": "2017 uLoL Campus Series Week 2: University of Texas vs UNC",
            "broadcaster_language": "en",
            "display_name": "Riot Games",
            "game": "League of Legends",
            "language": "en",
            "_id": 36029255,
            "name": "riotgames",
            "created_at": "2012-09-08T06:53:10Z",
            "updated_at": "2017-02-04T20:06:29Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/riotgames-profile_image-4be3ad99629ac9ba-300x300.jpeg",
            "banner": null,
            "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/riotgames-channel_offline_image-695d19948b70b6b3-1920x1080.jpeg",
            "background": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/riotgames-profile_banner-b75ec75838949ca8-480.png",
            "profile_banner_background_color": null,
            "url": "https://www.twitch.tv/riotgames",
            "views": 889813487,
            "followers": 2364514,
            "_links": {
                "self": "https://api.twitch.tv/kraken/channels/riotgames",
                "follows": "https://api.twitch.tv/kraken/channels/riotgames/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/riotgames/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/riotgames/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/riotgames",
                "features": "https://api.twitch.tv/kraken/channels/riotgames/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/riotgames/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/riotgames/editors",
                "teams": "https://api.twitch.tv/kraken/channels/riotgames/teams",
                "videos": "https://api.twitch.tv/kraken/channels/riotgames/videos"
            }
        },
        {
            "mature": false,
            "partner": false,
            "status": "RERUN: FaZe vs. NiP [Train] Map 2 - Semifinal - IEM Oakland 2016",
            "broadcaster_language": "en",
            "display_name": "ESL_CSGO",
            "game": "Counter-Strike: Global Offensive",
            "language": "en",
            "_id": 31239503,
            "name": "esl_csgo",
            "created_at": "2012-06-11T13:36:21Z",
            "updated_at": "2017-02-04T20:20:18Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_csgo-profile_image-546a0c1883798a41-300x300.jpeg",
            "banner": null,
            "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_csgo-channel_offline_image-c9f885982daa1c83-1920x1080.png",
            "background": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_csgo-profile_banner-0d10712c29995dc2-480.jpeg",
            "profile_banner_background_color": null,
            "url": "https://www.twitch.tv/esl_csgo",
            "views": 216953592,
            "followers": 1829736,
            "_links": {
                "self": "https://api.twitch.tv/kraken/channels/esl_csgo",
                "follows": "https://api.twitch.tv/kraken/channels/esl_csgo/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/esl_csgo/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/esl_csgo/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/esl_csgo",
                "features": "https://api.twitch.tv/kraken/channels/esl_csgo/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/esl_csgo/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/esl_csgo/editors",
                "teams": "https://api.twitch.tv/kraken/channels/esl_csgo/teams",
                "videos": "https://api.twitch.tv/kraken/channels/esl_csgo/videos"
            }
        },
        {
            "mature": false,
            "partner": false,
            "status": "Next Stream: Sunday @ 4 AM PST / 7 AM EST / NOON GMT - follow @Nightbloo on Twitter for more updates",
            "broadcaster_language": "en",
            "display_name": "Nightblue3",
            "game": "Counter-Strike: Global Offensive",
            "language": "en",
            "_id": 26946000,
            "name": "nightblue3",
            "created_at": "2011-12-21T18:18:40Z",
            "updated_at": "2017-02-04T20:11:01Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/nightblue3-profile_image-971af92f1d5dead6-300x300.png",
            "banner": null,
            "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/nightblue3-channel_offline_image-4cc024a7516eedf4-1920x1080.jpeg",
            "background": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/nightblue3-profile_banner-702bb40e6e0df38e-480.jpeg",
            "profile_banner_background_color": null,
            "url": "https://www.twitch.tv/nightblue3",
            "views": 163408001,
            "followers": 1796718,
            "_links": {
                "self": "https://api.twitch.tv/kraken/channels/nightblue3",
                "follows": "https://api.twitch.tv/kraken/channels/nightblue3/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/nightblue3/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/nightblue3/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/nightblue3",
                "features": "https://api.twitch.tv/kraken/channels/nightblue3/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/nightblue3/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/nightblue3/editors",
                "teams": "https://api.twitch.tv/kraken/channels/nightblue3/teams",
                "videos": "https://api.twitch.tv/kraken/channels/nightblue3/videos"
            }
        },
        {
            "mature": true,
            "partner": false,
            "status": "rust then cs later - @summit1g",
            "broadcaster_language": "en",
            "display_name": "summit1g",
            "game": "Rust",
            "language": "en",
            "_id": 26490481,
            "name": "summit1g",
            "created_at": "2011-12-01T06:33:31Z",
            "updated_at": "2017-02-04T20:06:23Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/summit1g-profile_image-87970af8826df799-300x300.png",
            "banner": null,
            "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/summit1g-channel_offline_image-e2f9a1df9e695ec1-1920x1080.png",
            "background": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/summit1g-profile_banner-da83b29c4dede9e4-480.png",
            "profile_banner_background_color": null,
            "url": "https://www.twitch.tv/summit1g",
            "views": 114554615,
            "followers": 1762949,
            "_links": {
                "self": "https://api.twitch.tv/kraken/channels/summit1g",
                "follows": "https://api.twitch.tv/kraken/channels/summit1g/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/summit1g/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/summit1g/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/summit1g",
                "features": "https://api.twitch.tv/kraken/channels/summit1g/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/summit1g/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/summit1g/editors",
                "teams": "https://api.twitch.tv/kraken/channels/summit1g/teams",
                "videos": "https://api.twitch.tv/kraken/channels/summit1g/videos"
            }
        },
        {
            "mature": false,
            "partner": false,
            "status": "the undisputed greatest league of legends player of all time goes on his smurf to show you what you need to do to carry at a diamond/master ",
            "broadcaster_language": "en",
            "display_name": "imaqtpie",
            "game": "League of Legends",
            "language": "en",
            "_id": 24991333,
            "name": "imaqtpie",
            "created_at": "2011-09-22T13:10:14Z",
            "updated_at": "2017-02-04T20:06:08Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/imaqtpie-profile_image-8efb10b7bed60d76-300x300.jpeg",
            "banner": null,
            "video_banner": null,
            "background": null,
            "profile_banner": null,
            "profile_banner_background_color": null,
            "url": "https://www.twitch.tv/imaqtpie",
            "views": 189263169,
            "followers": 1580673,
            "_links": {
                "self": "https://api.twitch.tv/kraken/channels/imaqtpie",
                "follows": "https://api.twitch.tv/kraken/channels/imaqtpie/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/imaqtpie/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/imaqtpie/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/imaqtpie",
                "features": "https://api.twitch.tv/kraken/channels/imaqtpie/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/imaqtpie/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/imaqtpie/editors",
                "teams": "https://api.twitch.tv/kraken/channels/imaqtpie/teams",
                "videos": "https://api.twitch.tv/kraken/channels/imaqtpie/videos"
            }
        },
        {
            "mature": true,
            "partner": false,
            "status": "Greatest Gamer EUW - Twitter: LIRIK - Store: dbh.la/lirik",
            "broadcaster_language": "en",
            "display_name": "LIRIK",
            "game": "H1Z1: King of the Kill",
            "language": "en",
            "_id": 23161357,
            "name": "lirik",
            "created_at": "2011-06-27T18:34:45Z",
            "updated_at": "2017-02-04T20:14:29Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/lirik-profile_image-476e7a592cdfed74-300x300.png",
            "banner": null,
            "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/lirik-channel_offline_image-af3bc6ef396c76ae-1920x1080.png",
            "background": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/lirik-profile_banner-cd63be39a747b629-480.png",
            "profile_banner_background_color": null,
            "url": "https://www.twitch.tv/lirik",
            "views": 156043857,
            "followers": 1571829,
            "_links": {
                "self": "https://api.twitch.tv/kraken/channels/lirik",
                "follows": "https://api.twitch.tv/kraken/channels/lirik/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/lirik/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/lirik/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/lirik",
                "features": "https://api.twitch.tv/kraken/channels/lirik/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/lirik/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/lirik/editors",
                "teams": "https://api.twitch.tv/kraken/channels/lirik/teams",
                "videos": "https://api.twitch.tv/kraken/channels/lirik/videos"
            }
        },
        {
            "mature": true,
            "partner": false,
            "status": "ASEFsefsEFadfsaefADwadawdawdvawdvbawda@Sodapoppintv @Northern_GG",
            "broadcaster_language": "en",
            "display_name": "sodapoppin",
            "game": "H1Z1: King of the Kill",
            "language": "en",
            "_id": 26301881,
            "name": "sodapoppin",
            "created_at": "2011-11-22T04:40:56Z",
            "updated_at": "2017-02-04T20:06:09Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/sodapoppin-profile_image-10049b6200f90c14-300x300.png",
            "banner": null,
            "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/sodapoppin-channel_offline_image-2040c6fcacec48db-1920x1080.jpeg",
            "background": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/sodapoppin-profile_banner-1c050aa5aed3558d-480.png",
            "profile_banner_background_color": null,
            "url": "https://www.twitch.tv/sodapoppin",
            "views": 148362109,
            "followers": 1394003,
            "_links": {
                "self": "https://api.twitch.tv/kraken/channels/sodapoppin",
                "follows": "https://api.twitch.tv/kraken/channels/sodapoppin/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/sodapoppin/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/sodapoppin/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/sodapoppin",
                "features": "https://api.twitch.tv/kraken/channels/sodapoppin/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/sodapoppin/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/sodapoppin/editors",
                "teams": "https://api.twitch.tv/kraken/channels/sodapoppin/teams",
                "videos": "https://api.twitch.tv/kraken/channels/sodapoppin/videos"
            }
        },
        {
            "mature": false,
            "partner": false,
            "status": "MINECRAFT FACTIONS N STUFF w/ Crainer and SSundee",
            "broadcaster_language": "en",
            "display_name": "CaptainSparklez",
            "game": "Minecraft",
            "language": "en",
            "_id": 15554591,
            "name": "captainsparklez",
            "created_at": "2010-09-12T23:55:54Z",
            "updated_at": "2017-02-04T20:02:23Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/captainsparklez-profile_image-fe5ae89fd8b8ed0f-300x300.png",
            "banner": null,
            "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/captainsparklez-channel_offline_image-09cd1f7bc10b44a4-1920x1080.png",
            "background": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/captainsparklez-profile_banner-bc17a6142e2b6200-480.png",
            "profile_banner_background_color": null,
            "url": "https://www.twitch.tv/captainsparklez",
            "views": 20548220,
            "followers": 1296067,
            "_links": {
                "self": "https://api.twitch.tv/kraken/channels/captainsparklez",
                "follows": "https://api.twitch.tv/kraken/channels/captainsparklez/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/captainsparklez/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/captainsparklez/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/captainsparklez",
                "features": "https://api.twitch.tv/kraken/channels/captainsparklez/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/captainsparklez/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/captainsparklez/editors",
                "teams": "https://api.twitch.tv/kraken/channels/captainsparklez/teams",
                "videos": "https://api.twitch.tv/kraken/channels/captainsparklez/videos"
            }
        },
        {
            "mature": false,
            "partner": false,
            "status": "Some lovely soloq before bed",
            "broadcaster_language": "en",
            "display_name": "TSM_Bjergsen",
            "game": "League of Legends",
            "language": "en",
            "_id": 38421618,
            "name": "tsm_bjergsen",
            "created_at": "2012-12-12T18:51:04Z",
            "updated_at": "2017-02-04T20:06:00Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/tsm_bjergsen-profile_image-ba41a683271a8848-300x300.jpeg",
            "banner": null,
            "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/tsm_bjergsen-channel_offline_image-d9fc3cc087eb1521-1920x1080.png",
            "background": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/tsm_bjergsen-profile_banner-7286a9fd5f76a349-480.png",
            "profile_banner_background_color": null,
            "url": "https://www.twitch.tv/tsm_bjergsen",
            "views": 82251145,
            "followers": 1270735,
            "_links": {
                "self": "https://api.twitch.tv/kraken/channels/tsm_bjergsen",
                "follows": "https://api.twitch.tv/kraken/channels/tsm_bjergsen/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/tsm_bjergsen/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/tsm_bjergsen/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/tsm_bjergsen",
                "features": "https://api.twitch.tv/kraken/channels/tsm_bjergsen/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/tsm_bjergsen/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/tsm_bjergsen/editors",
                "teams": "https://api.twitch.tv/kraken/channels/tsm_bjergsen/teams",
                "videos": "https://api.twitch.tv/kraken/channels/tsm_bjergsen/videos"
            }
        }
    ]
}
}
const streams = {
    "_total": 51057,
    "_links": {
        "self": "https://api.twitch.tv/kraken/search/streams?limit=10&query=%2A",
        "next": "https://api.twitch.tv/kraken/search/streams?limit=10&offset=10&query=%2A"
    },
    "streams": [
        {
            "_id": 24419594736,
            "game": "League of Legends",
            "viewers": 86750,
            "video_height": 1080,
            "average_fps": 60.7878945995,
            "delay": 0,
            "created_at": "2017-02-03T14:59:33Z",
            "is_playlist": false,
            "preview": {
                "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_eulcs1-80x45.jpg",
                "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_eulcs1-320x180.jpg",
                "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_eulcs1-640x360.jpg",
                "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_eulcs1-{width}x{height}.jpg"
            },
            "channel": {
                "mature": false,
                "partner": false,
                "status": "EU LCS: VIT vs. H2K | GIA vs. G2",
                "broadcaster_language": "en",
                "display_name": "EULCS1",
                "game": "League of Legends",
                "language": "en",
                "_id": 124422593,
                "name": "eulcs1",
                "created_at": "2016-05-16T18:00:12Z",
                "updated_at": "2017-02-03T19:35:13Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/eulcs1-profile_image-71def080ff1b2fc3-300x300.png",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eulcs1-channel_offline_image-a166db92e96d8890-1920x1080.jpeg",
                "background": null,
                "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eulcs1-profile_banner-4d84453aed159206-480.jpeg",
                "profile_banner_background_color": null,
                "url": "https://www.twitch.tv/eulcs1",
                "views": 27504336,
                "followers": 249215,
                "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/eulcs1",
                    "follows": "https://api.twitch.tv/kraken/channels/eulcs1/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/eulcs1/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/eulcs1/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/eulcs1",
                    "features": "https://api.twitch.tv/kraken/channels/eulcs1/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/eulcs1/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/eulcs1/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/eulcs1/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/eulcs1/videos"
                }
            },
            "_links": {
                "self": "https://api.twitch.tv/kraken/streams/eulcs1"
            }
        },
        {
            "_id": 24420501920,
            "game": "Tom Clancy's Ghost Recon: Wildlands",
            "viewers": 40977,
            "video_height": 720,
            "average_fps": 60.9560474816,
            "delay": 0,
            "created_at": "2017-02-03T17:04:30Z",
            "is_playlist": false,
            "preview": {
                "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_lirik-80x45.jpg",
                "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_lirik-320x180.jpg",
                "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_lirik-640x360.jpg",
                "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_lirik-{width}x{height}.jpg"
            },
            "channel": {
                "mature": true,
                "partner": false,
                "status": "Potato Recon - Twitter: @LIRIK - Store: dbh.la/lirik ",
                "broadcaster_language": "en",
                "display_name": "LIRIK",
                "game": "Tom Clancy's Ghost Recon: Wildlands",
                "language": "en",
                "_id": 23161357,
                "name": "lirik",
                "created_at": "2011-06-27T18:34:45Z",
                "updated_at": "2017-02-03T19:36:11Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/lirik-profile_image-476e7a592cdfed74-300x300.png",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/lirik-channel_offline_image-af3bc6ef396c76ae-1920x1080.png",
                "background": null,
                "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/lirik-profile_banner-cd63be39a747b629-480.png",
                "profile_banner_background_color": null,
                "url": "https://www.twitch.tv/lirik",
                "views": 155838984,
                "followers": 1570901,
                "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/lirik",
                    "follows": "https://api.twitch.tv/kraken/channels/lirik/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/lirik/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/lirik/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/lirik",
                    "features": "https://api.twitch.tv/kraken/channels/lirik/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/lirik/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/lirik/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/lirik/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/lirik/videos"
                }
            },
            "_links": {
                "self": "https://api.twitch.tv/kraken/streams/lirik"
            }
        },
        {
            "_id": 24420467280,
            "game": "IRL",
            "viewers": 27971,
            "video_height": 1080,
            "average_fps": 60,
            "delay": 0,
            "created_at": "2017-02-03T17:00:33Z",
            "is_playlist": false,
            "preview": {
                "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_gronkh-80x45.jpg",
                "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_gronkh-320x180.jpg",
                "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_gronkh-640x360.jpg",
                "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_gronkh-{width}x{height}.jpg"
            },
            "channel": {
                "mature": false,
                "partner": false,
                "status": "★ #FreiAb18 (ಥ﹏ಥ) HEUTE ab 18 Uhr! ★",
                "broadcaster_language": "de",
                "display_name": "Gronkh",
                "game": "IRL",
                "language": "de",
                "_id": 12875057,
                "name": "gronkh",
                "created_at": "2010-05-31T13:45:53Z",
                "updated_at": "2017-02-03T19:36:08Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/gronkh-profile_image-76b34139eaa46bb5-300x300.png",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/gronkh-channel_offline_image-eb70f551d9327737-1920x1080.jpeg",
                "background": null,
                "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/gronkh-profile_banner-1b26d17bba00a4fd-480.png",
                "profile_banner_background_color": null,
                "url": "https://www.twitch.tv/gronkh",
                "views": 28891293,
                "followers": 627574,
                "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/gronkh",
                    "follows": "https://api.twitch.tv/kraken/channels/gronkh/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/gronkh/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/gronkh/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/gronkh",
                    "features": "https://api.twitch.tv/kraken/channels/gronkh/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/gronkh/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/gronkh/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/gronkh/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/gronkh/videos"
                }
            },
            "_links": {
                "self": "https://api.twitch.tv/kraken/streams/gronkh"
            }
        },
        {
            "_id": 24420782688,
            "game": "FIFA 17",
            "viewers": 20335,
            "video_height": 1080,
            "average_fps": 61.5384615385,
            "delay": 0,
            "created_at": "2017-02-03T17:38:01Z",
            "is_playlist": false,
            "preview": {
                "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_castro_1021-80x45.jpg",
                "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_castro_1021-320x180.jpg",
                "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_castro_1021-640x360.jpg",
                "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_castro_1021-{width}x{height}.jpg"
            },
            "channel": {
                "mature": false,
                "partner": false,
                "status": "Skinny streamer getting buff. Click me.",
                "broadcaster_language": "en",
                "display_name": "Castro_1021",
                "game": "FIFA 17",
                "language": "en",
                "_id": 52091823,
                "name": "castro_1021",
                "created_at": "2013-11-24T08:42:28Z",
                "updated_at": "2017-02-03T19:36:04Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/castro_1021-profile_image-a9bec317de27c4f5-300x300.jpeg",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/castro_1021-channel_offline_image-1424d440df484eb3-1920x1080.png",
                "background": null,
                "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/castro_1021-profile_banner-a2bfbe534844e45e-480.jpeg",
                "profile_banner_background_color": null,
                "url": "https://www.twitch.tv/castro_1021",
                "views": 28456983,
                "followers": 1146457,
                "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/castro_1021",
                    "follows": "https://api.twitch.tv/kraken/channels/castro_1021/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/castro_1021/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/castro_1021/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/castro_1021",
                    "features": "https://api.twitch.tv/kraken/channels/castro_1021/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/castro_1021/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/castro_1021/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/castro_1021/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/castro_1021/videos"
                }
            },
            "_links": {
                "self": "https://api.twitch.tv/kraken/streams/castro_1021"
            }
        },
        {
            "_id": 24419453168,
            "game": "Tom Clancy's Rainbow Six: Siege",
            "viewers": 19558,
            "video_height": 720,
            "average_fps": 60.9794628752,
            "delay": 0,
            "created_at": "2017-02-03T14:36:35Z",
            "is_playlist": false,
            "preview": {
                "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_rainbow6-80x45.jpg",
                "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_rainbow6-320x180.jpg",
                "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_rainbow6-640x360.jpg",
                "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_rainbow6-{width}x{height}.jpg"
            },
            "channel": {
                "mature": false,
                "partner": false,
                "status": "Six Invitational - Day One",
                "broadcaster_language": "en",
                "display_name": "Rainbow6",
                "game": "Tom Clancy's Rainbow Six: Siege",
                "language": "en",
                "_id": 65171890,
                "name": "rainbow6",
                "created_at": "2014-06-27T13:51:55Z",
                "updated_at": "2017-02-03T19:49:58Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/rainbow6-profile_image-ec04da2d1f541b1d-300x300.png",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/rainbow6-channel_offline_image-c7312056c6daa164-1920x1080.jpeg",
                "background": null,
                "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/rainbow6-profile_banner-e52ed560147fa5eb-480.jpeg",
                "profile_banner_background_color": null,
                "url": "https://www.twitch.tv/rainbow6",
                "views": 5252113,
                "followers": 126347,
                "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/rainbow6",
                    "follows": "https://api.twitch.tv/kraken/channels/rainbow6/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/rainbow6/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/rainbow6/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/rainbow6",
                    "features": "https://api.twitch.tv/kraken/channels/rainbow6/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/rainbow6/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/rainbow6/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/rainbow6/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/rainbow6/videos"
                }
            },
            "_links": {
                "self": "https://api.twitch.tv/kraken/streams/rainbow6"
            }
        },
        {
            "_id": 24420569776,
            "game": "Rust",
            "viewers": 17889,
            "video_height": 720,
            "average_fps": 62.1387283237,
            "delay": 0,
            "created_at": "2017-02-03T17:12:36Z",
            "is_playlist": false,
            "preview": {
                "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_summit1g-80x45.jpg",
                "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_summit1g-320x180.jpg",
                "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_summit1g-640x360.jpg",
                "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_summit1g-{width}x{height}.jpg"
            },
            "channel": {
                "mature": true,
                "partner": false,
                "status": "Rust then some Rank G games later - @summit1g",
                "broadcaster_language": "en",
                "display_name": "summit1g",
                "game": "Rust",
                "language": "en",
                "_id": 26490481,
                "name": "summit1g",
                "created_at": "2011-12-01T06:33:31Z",
                "updated_at": "2017-02-03T19:35:46Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/summit1g-profile_image-87970af8826df799-300x300.png",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/summit1g-channel_offline_image-e2f9a1df9e695ec1-1920x1080.png",
                "background": null,
                "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/summit1g-profile_banner-da83b29c4dede9e4-480.png",
                "profile_banner_background_color": null,
                "url": "https://www.twitch.tv/summit1g",
                "views": 114278182,
                "followers": 1760891,
                "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/summit1g",
                    "follows": "https://api.twitch.tv/kraken/channels/summit1g/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/summit1g/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/summit1g/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/summit1g",
                    "features": "https://api.twitch.tv/kraken/channels/summit1g/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/summit1g/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/summit1g/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/summit1g/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/summit1g/videos"
                }
            },
            "_links": {
                "self": "https://api.twitch.tv/kraken/streams/summit1g"
            }
        },
        {
            "_id": 24417968976,
            "game": "Magic: The Gathering",
            "viewers": 16801,
            "video_height": 1080,
            "average_fps": 30.9375,
            "delay": 0,
            "created_at": "2017-02-03T08:56:47Z",
            "is_playlist": false,
            "preview": {
                "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_magic-80x45.jpg",
                "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_magic-320x180.jpg",
                "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_magic-640x360.jpg",
                "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_magic-{width}x{height}.jpg"
            },
            "channel": {
                "mature": false,
                "partner": false,
                "status": "Pro Tour Aether Revolt - Day 1",
                "broadcaster_language": "en",
                "display_name": "Magic",
                "game": "Magic: The Gathering",
                "language": "en",
                "_id": 26991613,
                "name": "magic",
                "created_at": "2011-12-23T18:03:44Z",
                "updated_at": "2017-02-03T19:35:57Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/magic-profile_image-06ea83a772d44824-300x300.jpeg",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/magic-channel_offline_image-dacd22b707f80b6a-1920x1080.jpeg",
                "background": null,
                "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/magic-profile_banner-68b1db6640cc85cb-480.jpeg",
                "profile_banner_background_color": null,
                "url": "https://www.twitch.tv/magic",
                "views": 48077183,
                "followers": 120044,
                "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/magic",
                    "follows": "https://api.twitch.tv/kraken/channels/magic/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/magic/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/magic/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/magic",
                    "features": "https://api.twitch.tv/kraken/channels/magic/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/magic/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/magic/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/magic/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/magic/videos"
                }
            },
            "_links": {
                "self": "https://api.twitch.tv/kraken/streams/magic"
            }
        },
        {
            "_id": 24419876080,
            "game": "Hearthstone",
            "viewers": 15396,
            "video_height": 1080,
            "average_fps": 60,
            "delay": 0,
            "created_at": "2017-02-03T15:41:19Z",
            "is_playlist": false,
            "preview": {
                "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_savjz-80x45.jpg",
                "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_savjz-320x180.jpg",
                "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_savjz-640x360.jpg",
                "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_savjz-{width}x{height}.jpg"
            },
            "channel": {
                "mature": false,
                "partner": false,
                "status": "Savjz Nefarian Priest",
                "broadcaster_language": "en",
                "display_name": "Savjz",
                "game": "Hearthstone",
                "language": "fi",
                "_id": 43131877,
                "name": "savjz",
                "created_at": "2013-05-03T12:27:19Z",
                "updated_at": "2017-02-03T19:35:40Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/savjz-profile_image-fcb7a4314f7a9e31-300x300.jpeg",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/savjz-channel_offline_image-b0f25dee0c36d78d-1920x1080.png",
                "background": null,
                "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/savjz-profile_banner-1980171399851b4b-480.png",
                "profile_banner_background_color": null,
                "url": "https://www.twitch.tv/savjz",
                "views": 21714506,
                "followers": 288897,
                "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/savjz",
                    "follows": "https://api.twitch.tv/kraken/channels/savjz/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/savjz/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/savjz/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/savjz",
                    "features": "https://api.twitch.tv/kraken/channels/savjz/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/savjz/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/savjz/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/savjz/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/savjz/videos"
                }
            },
            "_links": {
                "self": "https://api.twitch.tv/kraken/streams/savjz"
            }
        },
        {
            "_id": 24419596320,
            "game": "League of Legends",
            "viewers": 14463,
            "video_height": 1080,
            "average_fps": 59.9496221662,
            "delay": 0,
            "created_at": "2017-02-03T14:59:47Z",
            "is_playlist": false,
            "preview": {
                "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_summonersinnlive-80x45.jpg",
                "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_summonersinnlive-320x180.jpg",
                "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_summonersinnlive-640x360.jpg",
                "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_summonersinnlive-{width}x{height}.jpg"
            },
            "channel": {
                "mature": false,
                "partner": false,
                "status": "LCS Spring Split - Woche 3, Tag 2 [GER] #LCSGer",
                "broadcaster_language": "de",
                "display_name": "SummonersInnLive",
                "game": "League of Legends",
                "language": "de",
                "_id": 40336240,
                "name": "summonersinnlive",
                "created_at": "2013-02-15T10:30:40Z",
                "updated_at": "2017-02-03T19:35:06Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/summonersinnlive-profile_image-f177e86c384b45af-300x300.png",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/summonersinnlive-channel_offline_image-e4edb2f08f3f715e-1920x1080.png",
                "background": null,
                "profile_banner": null,
                "profile_banner_background_color": null,
                "url": "https://www.twitch.tv/summonersinnlive",
                "views": 48003590,
                "followers": 276825,
                "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/summonersinnlive",
                    "follows": "https://api.twitch.tv/kraken/channels/summonersinnlive/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/summonersinnlive/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/summonersinnlive/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/summonersinnlive",
                    "features": "https://api.twitch.tv/kraken/channels/summonersinnlive/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/summonersinnlive/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/summonersinnlive/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/summonersinnlive/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/summonersinnlive/videos"
                }
            },
            "_links": {
                "self": "https://api.twitch.tv/kraken/streams/summonersinnlive"
            }
        },
        {
            "_id": 24419755568,
            "game": "League of Legends",
            "viewers": 12897,
            "video_height": 720,
            "average_fps": 60.8547976224,
            "delay": 0,
            "created_at": "2017-02-03T15:24:03Z",
            "is_playlist": false,
            "preview": {
                "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ogaminglol-80x45.jpg",
                "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ogaminglol-320x180.jpg",
                "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ogaminglol-640x360.jpg",
                "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ogaminglol-{width}x{height}.jpg"
            },
            "channel": {
                "mature": false,
                "partner": false,
                "status": "LCS EU - GIA vs G2 - W3D2",
                "broadcaster_language": "fr",
                "display_name": "OgamingLoL",
                "game": "League of Legends",
                "language": "fr",
                "_id": 71852533,
                "name": "ogaminglol",
                "created_at": "2014-09-24T14:59:47Z",
                "updated_at": "2017-02-03T19:35:37Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/ogaminglol-profile_image-5cb504af49b99670-300x300.jpeg",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/ogaminglol-channel_offline_image-0f48859f468e6d9f-1920x1080.png",
                "background": null,
                "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/ogaminglol-profile_banner-a46b31609aa510b5-480.png",
                "profile_banner_background_color": null,
                "url": "https://www.twitch.tv/ogaminglol",
                "views": 58507799,
                "followers": 177829,
                "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/ogaminglol",
                    "follows": "https://api.twitch.tv/kraken/channels/ogaminglol/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/ogaminglol/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/ogaminglol/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/ogaminglol",
                    "features": "https://api.twitch.tv/kraken/channels/ogaminglol/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/ogaminglol/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/ogaminglol/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/ogaminglol/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/ogaminglol/videos"
                }
            },
            "_links": {
                "self": "https://api.twitch.tv/kraken/streams/ogaminglol"
            }
        }
    ]
};

export  {
    streams,
    channels,
    }
